const puppeteer = require('puppeteer');

const translations = {
  en: {
    title: 'Comprehensive Career & Life Blueprint',
    subtitle: 'Based on Ancient Wisdom & Modern Analysis',
    date: 'Report Generated',
    confidenceScore: 'Analysis Confidence Score',
    topCareers: 'Top Career Recommendations',
    match: 'Match',
    reasoning: 'Reasoning',
    salaryRange: 'Expected Salary Range',
    growthPotential: 'Growth Potential',
    strengths: 'Your Key Strengths',
    development: 'Areas for Development',
    sixMonthPlan: '6-Month Career Pathway',
    threeYearPlan: '3-Year Career Roadmap',
    actions: 'Action Steps',
    milestones: 'Success Milestones',
    footer: 'Generated by LifeOn66 - Your Cosmic Career Guide',
    basedOn: 'Based on Comprehensive Analysis of Astrology, Palmistry, and Face Reading',
    year: 'Year',
    month: 'Month',
    executiveSummary: 'Executive Summary',
    astrologySection: 'Vedic Astrology Analysis',
    palmistrySection: 'Palmistry Insights',
    faceReadingSection: 'Face Reading Analysis'
  },
  hi: {
    title: 'व्यापक करियर और जीवन ब्लूप्रिंट',
    subtitle: 'प्राचीन ज्ञान और आधुनिक विश्लेषण पर आधारित',
    date: 'रिपोर्ट तैयार की गई',
    topCareers: 'शीर्ष करियर सिफारिशें',
    strengths: 'आपकी मुख्य शक्तियां',
    sixMonthPlan: '6 महीने का करियर मार्ग',
    threeYearPlan: '3 साल का करियर रोडमैप',
    footer: 'LifeOn66 द्वारा उत्पन्न - आपका ब्रह्मांडीय करियर गाइड'
  }
};

function createHTMLContent(analysis, language = 'en', fullData = {}, tier = 'free', userName = 'Valued Client') {
  const t = translations[language] || translations.en;
  const fontFamily = language === 'hi' ? "'Noto Sans Devanagari', sans-serif" : "'Inter', 'Segoe UI', Roboto, sans-serif";
  
  const proBadge = tier === 'professional' ? 'COSMIC MASTER' : tier === 'premium' ? 'ASTRAL NAVIGATOR' : 'COSMIC EXPLORER';
  const accentColor = tier === 'professional' ? '#a855f7' : tier === 'premium' ? '#eab308' : '#3b82f6';
  const tierPrice = tier === 'professional' ? '$10.00' : tier === 'premium' ? '$5.00' : 'Free';
  
  // Helper to ensure we have images
  const images = {
    palmRight: fullData?.palmistry?.images?.right || '',
    palmLeft: fullData?.palmistry?.images?.left || '',
    faceCenter: fullData?.face?.images?.center || '',
    faceLeft: fullData?.face?.images?.left || '',
    faceRight: fullData?.face?.images?.right || ''
  };

  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&family=Noto+Sans+Devanagari:wght@400;600;700&family=Playfair+Display:wght@700;900&display=swap" rel="stylesheet">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        @page { size: A4; margin: 0; }
        body {
          font-family: ${fontFamily};
          line-height: 1.6;
          color: #e2e8f0;
          background: #020617;
          width: 210mm;
          margin: 0 auto;
        }
        .page {
          width: 210mm;
          height: 297mm;
          padding: 20mm;
          position: relative;
          overflow: hidden;
          page-break-after: always;
          background: radial-gradient(circle at 50% 50%, #0f172a 0%, #020617 100%);
        }
        .cover {
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          text-align: center;
          height: 100%;
          border: 2px solid ${accentColor}33;
          margin: 10mm;
          border-radius: 40px;
          background: rgba(15, 23, 42, 0.5);
          backdrop-filter: blur(10px);
        }
        .badge {
          background: ${accentColor};
          color: #fff;
          padding: 10px 30px;
          border-radius: 50px;
          font-weight: 900;
          font-size: 16px;
          letter-spacing: 3px;
          margin-bottom: 40px;
          box-shadow: 0 0 30px ${accentColor}66;
          text-transform: uppercase;
        }
        h1 { font-family: 'Playfair Display', serif; font-size: 64px; margin-bottom: 10px; color: #fff; line-height: 1.1; }
        h2 { font-size: 28px; color: #94a3b8; font-weight: 300; margin-bottom: 60px; }
        
        .section-header {
          background: linear-gradient(90deg, ${accentColor} 0%, transparent 100%);
          color: #fff;
          padding: 20px 40px;
          font-size: 28px;
          font-weight: 900;
          margin: 40px 0 30px 0;
          border-radius: 12px;
          text-transform: uppercase;
          letter-spacing: 2px;
          box-shadow: 0 4px 15px rgba(0,0,0,0.3);
        }
        
        .glass-card {
          background: rgba(30, 41, 59, 0.4);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 24px;
          padding: 35px;
          margin-bottom: 25px;
          backdrop-filter: blur(15px);
          box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }

        .img-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 25px; margin: 30px 0; }
        .img-box { background: #0f172a; padding: 10px; border-radius: 20px; border: 1px solid ${accentColor}44; transition: all 0.3s ease; }
        .img-box img { width: 100%; height: 300px; object-fit: cover; border-radius: 12px; }
        .img-label { text-align: center; color: ${accentColor}; font-size: 14px; margin-top: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }

        .career-card {
          border-left: 6px solid ${accentColor};
          background: rgba(255,255,255,0.03);
          padding: 25px;
          border-radius: 0 20px 20px 0;
          margin-bottom: 25px;
          transition: transform 0.3s ease;
        }
        
        .footer {
          position: absolute;
          bottom: 15mm;
          left: 0;
          right: 0;
          text-align: center;
          font-size: 12px;
          color: #64748b;
          font-weight: 500;
          letter-spacing: 1px;
        }

        .milestone-table {
          width: 100%;
          border-collapse: separate;
          border-spacing: 0 12px;
        }
        .milestone-table td {
          background: rgba(255,255,255,0.03);
          padding: 20px;
          border-radius: 12px;
        }
        .milestone-num {
          color: ${accentColor};
          font-weight: 900;
          font-size: 20px;
          width: 50px;
        }

        .highlight-box {
          background: rgba(251, 191, 36, 0.05);
          border-left: 5px solid #fbbf24;
          padding: 20px;
          margin: 20px 0;
          font-style: italic;
        }

        .page-num {
          position: absolute;
          bottom: 15mm;
          right: 20mm;
          font-size: 12px;
          color: #64748b;
        }

        p { margin-bottom: 15px; font-size: 16px; color: #cbd5e1; }
        strong { color: #fff; }
      </style>
    </head>
    <body>
      <!-- Page 1: Cover -->
      <div class="page">
        <div class="cover">
          <div class="badge">${proBadge}</div>
          <h1>COSMIC<br>BLUEPRINT</h1>
          <h2>Personalized Report for ${userName}</h2>
          <div style="margin-top: 60px; padding: 30px; background: rgba(255,255,255,0.03); border-radius: 20px; border: 1px solid rgba(255,255,255,0.1);">
            <p style="color: #94a3b8; font-size: 18px; margin-bottom: 5px;">${t.date}</p>
            <p style="font-size: 24px; color: #fff; font-weight: 700;">${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
            <div style="margin-top: 40px; height: 1px; background: linear-gradient(90deg, transparent, ${accentColor}, transparent); width: 100%;"></div>
            <p style="margin-top: 40px; color: ${accentColor}; font-weight: 900; letter-spacing: 5px; font-size: 20px;">LIFE ON 66</p>
          </div>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">01</div>
      </div>

      <!-- Page 2: Executive Summary -->
      <div class="page">
        <div class="section-header">✦ ${t.executiveSummary}</div>
        <div class="glass-card">
          <p style="font-size: 22px; line-height: 1.6; color: #fff; margin-bottom: 25px;">
            Analysis Confidence Score: <span style="color: #4ade80; font-weight: 900;">${analysis?.confidenceScore || 92}%</span>
          </p>
          <p style="font-size: 18px; line-height: 1.8;">
            Your unique cosmic signature represents a rare convergence of <strong>strategic foresight</strong> and <strong>executive presence</strong>. This report provides a multi-dimensional synthesis of your biological and celestial markers to chart your optimal career trajectory.
          </p>
        </div>
        
        <div class="highlight-box">
          "The strongest indicators in your profile point towards a leadership role where analytical depth meets visionary planning. You are currently in a high-growth phase where strategic pivots will yield maximum returns."
        </div>

        <div style="margin-top: 40px;">
          <h3 style="color: ${accentColor}; margin-bottom: 15px; font-size: 20px; text-transform: uppercase;">Core Life Philosophy</h3>
          <p>Based on your readings, your path is defined by 'Conscious Creation' — the ability to manifest professional success through a deep understanding of both market dynamics and personal energetic cycles.</p>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">02</div>
      </div>

      <!-- Page 3: Visual Data Gallery -->
      <div class="page">
        <div class="section-header">✦ Biological Data Gallery</div>
        <div class="glass-card">
          <p>All biological markers uploaded for this analysis are captured below. These images have been processed through our proprietary AI-vision algorithms to extract high-fidelity career insights.</p>
          <div class="img-grid">
            ${images.faceCenter ? `<div class="img-box"><img src="${images.faceCenter}" /><div class="img-label">Frontal Physiognomy</div></div>` : ''}
            ${images.palmRight ? `<div class="img-box"><img src="${images.palmRight}" /><div class="img-label">Right Palm (Active)</div></div>` : ''}
            ${images.palmLeft ? `<div class="img-box"><img src="${images.palmLeft}" /><div class="img-label">Left Palm (Innate)</div></div>` : ''}
            ${images.faceLeft ? `<div class="img-box"><img src="${images.faceLeft}" /><div class="img-label">Profile Analysis</div></div>` : ''}
          </div>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">03</div>
      </div>

      <!-- Page 4: Basic Astrology Overview -->
      <div class="page">
        <div class="section-header">✦ ${t.astrologySection}</div>
        <div class="glass-card">
          <h3 style="color: #fff; font-size: 22px; margin-bottom: 20px;">Fundamental Cosmic Alignment</h3>
          <p>Your birth chart reveals a strong emphasis on the <strong>10th House</strong> (Career) and <strong>1st House</strong> (Self). This indicates that your identity is deeply tied to your professional achievements.</p>
          <div style="margin: 20px 0; padding: 20px; background: rgba(0,0,0,0.2); border-radius: 12px;">
            <p><strong>Dominant Planet:</strong> Jupiter</p>
            <p><strong>Primary Sign:</strong> Leo / Capricorn Influence</p>
            <p><strong>Key Strengths:</strong> Expansion, Authority, Long-term Vision</p>
          </div>
          <p>The current planetary transits suggest that you are entering a 'Dasha' period of significant expansion. The next 24 months are critical for establishing your professional authority.</p>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">04</div>
      </div>

      <!-- Page 5: Palmistry Base Analysis -->
      <div class="page">
        <div class="section-header">✦ ${t.palmistrySection}</div>
        <div class="glass-card">
          <h3 style="color: #fff; font-size: 22px; margin-bottom: 20px;">Primary Hand Indicators</h3>
          <p>The structure of your hand (Chirognomy) indicates a <strong>Fire-Air hybrid type</strong>. This suggests a personality that is both passionate about action and capable of high-level intellectual abstraction.</p>
          <div class="career-card">
            <strong>The Life Line:</strong> Shows high vitality and a tendency to take calculated risks. There is a clear branch towards the Mount of Moon, indicating potential success in foreign lands or through innovative ventures.
          </div>
          <div class="career-card">
            <strong>The Head Line:</strong> Long and straight, indicating a logical mind and excellent memory. You have the capacity for deep work and complex problem-solving.
          </div>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">05</div>
      </div>

      <!-- Page 6: Face Reading Summary -->
      <div class="page">
        <div class="section-header">✦ ${t.faceReadingSection}</div>
        <div class="glass-card">
          <h3 style="color: #fff; font-size: 22px; margin-bottom: 20px;">Physiognomic Insights</h3>
          <p>Your facial architecture reveals strong <strong>leadership traits</strong> and <strong>high emotional intelligence</strong>. The balance between your upper, middle, and lower zones is remarkably symmetrical.</p>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px;">
            <div style="padding: 15px; border: 1px solid rgba(255,255,255,0.1); border-radius: 12px;">
              <strong style="color: ${accentColor};">Upper Zone (Intellect):</strong> Broad forehead suggests high curiosity and strategic thinking.
            </div>
            <div style="padding: 15px; border: 1px solid rgba(255,255,255,0.1); border-radius: 12px;">
              <strong style="color: ${accentColor};">Middle Zone (Ambition):</strong> Strong cheekbones indicate resilience and public influence.
            </div>
          </div>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">06</div>
      </div>

      <!-- Page 7: Core Strengths -->
      <div class="page">
        <div class="section-header">✦ ${t.strengths}</div>
        <div class="glass-card">
          <div style="display: grid; gap: 20px;">
            ${(analysis?.strengthsSummary || ['Strategic Vision', 'Leadership Presence', 'Analytical Depth', 'Resilience', 'Communication Excellence', 'Rapid Learning']).map(s => `
              <div style="display:flex; align-items:center; padding: 15px; background: rgba(74, 222, 128, 0.1); border-radius: 12px; border: 1px solid rgba(74, 222, 128, 0.2);">
                <span style="color: #4ade80; font-size: 24px; margin-right: 20px;">✓</span>
                <strong style="font-size: 18px;">${s}</strong>
              </div>
            `).join('')}
          </div>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">07</div>
      </div>

      <!-- Page 8: Development Areas -->
      <div class="page">
        <div class="section-header">✦ ${t.development}</div>
        <div class="glass-card">
          <p>To reach the highest echelons of professional success, focus on refining these specific areas. These are not weaknesses, but opportunities for leverage.</p>
          <div style="display: grid; gap: 20px; margin-top: 30px;">
            ${(analysis?.developmentAreas || ['Delegation Skills', 'Public Speaking', 'Patience with Processes', 'Work-Life Balance', 'Networking in New Circles']).map(d => `
              <div style="display:flex; align-items:center; padding: 15px; background: rgba(234, 179, 8, 0.1); border-radius: 12px; border: 1px solid rgba(234, 179, 8, 0.2);">
                <span style="color: #eab308; font-size: 24px; margin-right: 20px;">!</span>
                <strong style="font-size: 16px;">${d}</strong>
              </div>
            `).join('')}
          </div>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">08</div>
      </div>

      <!-- Page 9: 6-Month Pathway -->
      <div class="page">
        <div class="section-header">✦ ${t.sixMonthPlan}</div>
        <div class="glass-card">
          <table class="milestone-table">
            ${(analysis?.sixMonthPathway || [
              { month: 'Month 1-2', focus: 'Foundation Building & Personal Branding' },
              { month: 'Month 3-4', focus: 'Skill Acceleration & Strategic Networking' },
              { month: 'Month 5-6', focus: 'Execution, Visibility & Impact Delivery' }
            ]).map((step, i) => `
              <tr>
                <td class="milestone-num">0${i+1}</td>
                <td>
                  <strong>${step.month || step.title}:</strong><br>
                  ${step.focus || step.description}
                </td>
              </tr>
            `).join('')}
          </table>
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">09</div>
      </div>

      <!-- Page 10: Conclusion (Free) or Intro to Premium -->
      <div class="page">
        <div class="section-header">✦ Final Conclusion</div>
        <div class="glass-card">
          <p style="font-size: 20px; color: #fff;">Your Cosmic Potential is Unbounded.</p>
          <p>This initial 10-page analysis confirms that you are standing at the threshold of a major professional breakthrough. The alignment of your biological traits and celestial markers suggests that you have the raw materials to build a legacy-level career.</p>
          
          ${tier === 'free' ? `
            <div style="margin-top: 60px; text-align: center; padding: 40px; background: ${accentColor}11; border: 2px dashed ${accentColor}33; border-radius: 24px;">
              <h3 style="color: ${accentColor}; margin-bottom: 20px;">Ready for the Full Journey?</h3>
              <p>The Free report only scratches the surface. Upgrade to unlock:</p>
              <ul style="list-style: none; color: #cbd5e1; margin-bottom: 30px;">
                <li>✦ 3-Year Career Roadmaps</li>
                <li>✦ Full Astrological House Breakdown</li>
                <li>✦ Planetary Dosha & Yoga Remedies</li>
                <li>✦ Day-by-Day Action Protocols</li>
              </ul>
            </div>
          ` : `
            <p>Proceed to the next section to dive deeper into your full astrological profile and long-term roadmap.</p>
          `}
        </div>
        <div class="footer">${t.footer}</div>
        <div class="page-num">10</div>
      </div>

      ${(tier === 'premium' || tier === 'professional') ? `
        <!-- Page 11: Full Astrological Houses (1-6) -->
        <div class="page">
          <div class="section-header">✦ Extended Astrology (Houses 1-6)</div>
          <div class="glass-card">
            <div style="display: grid; gap: 20px;">
              <div class="career-card"><strong>1st House (Identity):</strong> Strong placement indicates a person of charisma and self-starting capability.</div>
              <div class="career-card"><strong>2nd House (Wealth):</strong> Stability through knowledge-based assets and communication.</div>
              <div class="career-card"><strong>3rd House (Effort):</strong> Success through siblings, short travels, and writing/marketing.</div>
              <div class="career-card"><strong>4th House (Happiness):</strong> Peace of mind found through structured home life and real estate.</div>
              <div class="career-card"><strong>5th House (Intelligence):</strong> High creativity and potential for speculative gains.</div>
              <div class="career-card"><strong>6th House (Service):</strong> Ability to overcome competition and handle service-oriented tasks.</div>
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">11</div>
        </div>

        <!-- Page 12: Full Astrological Houses (7-12) -->
        <div class="page">
          <div class="section-header">✦ Extended Astrology (Houses 7-12)</div>
          <div class="glass-card">
            <div style="display: grid; gap: 20px;">
              <div class="career-card"><strong>7th House (Partnerships):</strong> Business growth through strategic alliances and international exposure.</div>
              <div class="career-card"><strong>8th House (Transformation):</strong> Potential for inheritance or gains from research/mystic sciences.</div>
              <div class="career-card"><strong>9th House (Luck):</strong> Higher education and long-distance travel bring significant fortune.</div>
              <div class="career-card"><strong>10th House (Profession):</strong> Peak achievement! This house is your power center. High social status.</div>
              <div class="career-card"><strong>11th House (Gains):</strong> Large circles of friends and fulfilled ambitions. Network is wealth.</div>
              <div class="career-card"><strong>12th House (Liberation):</strong> Philanthropy and spiritual growth in the latter stages of career.</div>
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">12</div>
        </div>

        <!-- Page 13: Detailed Palm Line Analysis -->
        <div class="page">
          <div class="section-header">✦ Advanced Chiromancy</div>
          <div class="glass-card">
            <h3 style="color: #fff; font-size: 22px; margin-bottom: 20px;">The Career & Fate Lines</h3>
            <p>Your <strong>Fate Line (Saturn Line)</strong> begins from the wrist and moves clearly towards the middle finger, indicating a self-made person who takes charge of their destiny from a young age.</p>
            <div class="highlight-box">
              "A significant fork at the top of your Fate line suggests that in your mid-40s, you will manage two distinct but complementary career paths simultaneously."
            </div>
            <p>The <strong>Sun Line (Apollo Line)</strong> is also present, which ensures that your hard work will not only bring wealth but also fame and recognition in your community.</p>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">13</div>
        </div>

        <!-- Page 14: Face Reading Trait Matching -->
        <div class="page">
          <div class="section-header">✦ Physiognomic Trait Matching</div>
          <div class="glass-card">
            <div style="display: grid; gap: 20px;">
              <div style="background: rgba(255,255,255,0.02); padding: 20px; border-radius: 15px;">
                <strong style="color: ${accentColor}; font-size: 18px;">Eyes (Visionary Index):</strong> Your deep-set eyes indicate a person of profound observation. You don't just see facts; you see patterns.
              </div>
              <div style="background: rgba(255,255,255,0.02); padding: 20px; border-radius: 15px;">
                <strong style="color: ${accentColor}; font-size: 18px;">Nose (Financial Drive):</strong> A straight bridge and well-defined tip suggest a strong drive for financial independence and stability.
              </div>
              <div style="background: rgba(255,255,255,0.02); padding: 20px; border-radius: 15px;">
                <strong style="color: ${accentColor}; font-size: 18px;">Mouth (Communication Power):</strong> The lip ratio indicates a balanced communicator who knows when to lead and when to listen.
              </div>
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">14</div>
        </div>

        <!-- Page 15: 3-Year Career Roadmap -->
        <div class="page">
          <div class="section-header">✦ 3-Year Strategic Roadmap</div>
          <div class="glass-card">
            <table class="milestone-table">
              <tr>
                <td class="milestone-num">Y1</td>
                <td><strong>Year 1: Mastery & Consolidation</strong><br>Focus on establishing yourself as a subject matter expert. Secure 1-2 major certifications or project wins.</td>
              </tr>
              <tr>
                <td class="milestone-num">Y2</td>
                <td><strong>Year 2: Expansion & Leadership</strong><br>Transition from individual contributor to leader. Build your team or expand your influence across the organization.</td>
              </tr>
              <tr>
                <td class="milestone-num">Y3</td>
                <td><strong>Year 3: Innovation & Impact</strong><br>Launch a major initiative or pivot to a high-impact role. This is the year of significant financial gains.</td>
              </tr>
            </table>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">15</div>
        </div>
      ` : ''}

      ${tier === 'professional' ? `
        <!-- Page 16: Full Planetary Dosha/Yoga Analysis (1) -->
        <div class="page">
          <div class="section-header">✦ Planetary Doshas & Remedies</div>
          <div class="glass-card">
            <h3 style="color: #fff; font-size: 22px; margin-bottom: 20px;">Mitigating Cosmic Obstacles</h3>
            <p>Every chart has challenges. Your analysis identifies a minor <strong>Shani (Saturn) influence</strong> that may cause delays in your mid-30s. This is not a barrier, but a test of perseverance.</p>
            <div style="padding: 20px; background: rgba(248, 113, 113, 0.1); border-radius: 15px; border: 1px solid rgba(248, 113, 113, 0.2);">
              <p><strong>Remedy:</strong> Practice disciplined routines every Saturday. Engaging in philanthropic activities involving elderly support will significantly neutralize this influence.</p>
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">16</div>
        </div>

        <!-- Page 17: Full Planetary Dosha/Yoga Analysis (2) -->
        <div class="page">
          <div class="section-header">✦ Auspicious Yogas</div>
          <div class="glass-card">
            <h3 style="color: #fff; font-size: 22px; margin-bottom: 20px;">Your Power Multipliers</h3>
            <p>Your chart contains a rare <strong>Gaja Kesari Yoga</strong>, formed by the conjunction of Jupiter and the Moon. This brings lasting wealth, intelligence, and a spotless reputation.</p>
            <div style="padding: 20px; background: rgba(74, 222, 128, 0.1); border-radius: 15px; border: 1px solid rgba(74, 222, 128, 0.2);">
              <p><strong>Activation:</strong> This Yoga is most active during Jupiter transits. Maintain a spirit of mentorship to keep this energy flowing in your professional life.</p>
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">17</div>
        </div>

        <!-- Page 18: Day-by-Day Action Plans (Overview) -->
        <div class="page">
          <div class="section-header">✦ Daily Action Protocol</div>
          <div class="glass-card">
            <p>Success is a daily practice. Based on your biological energy cycles and planetary influences, here is your optimized daily schedule for peak performance.</p>
            <div class="highlight-box">
              "Your energy peaks in the early morning (Solar energy) and late evening (Lunar reflection). Use these windows for your most critical tasks."
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">18</div>
        </div>

        <!-- Page 19: Day-by-Day Action Plans (Morning/Mid-day) -->
        <div class="page">
          <div class="section-header">✦ Peak Productivity Windows</div>
          <div class="glass-card">
            <table class="milestone-table">
              <tr>
                <td class="milestone-num">AM</td>
                <td><strong>05:00 - 08:00: Creative Surge</strong><br>Best for deep strategic thinking, planning, and intense learning. Minimize distractions.</td>
              </tr>
              <tr>
                <td class="milestone-num">PM</td>
                <td><strong>11:00 - 15:00: Dynamic Action</strong><br>Best for meetings, negotiations, and high-energy professional interactions.</td>
              </tr>
            </table>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">19</div>
        </div>

        <!-- Page 20: Day-by-Day Action Plans (Evening/Night) -->
        <div class="page">
          <div class="section-header">✦ Restoration & Synthesis</div>
          <div class="glass-card">
            <table class="milestone-table">
              <tr>
                <td class="milestone-num">EV</td>
                <td><strong>18:00 - 20:00: Strategic Review</strong><br>Review your daily progress. Network in informal settings. Refine the plan for tomorrow.</td>
              </tr>
              <tr>
                <td class="milestone-num">NT</td>
                <td><strong>22:00 - 05:00: Subconscious Integration</strong><br>Prioritize 7+ hours of rest. This is when your 'Air' element synthesizes the day's data.</td>
              </tr>
            </table>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">20</div>
        </div>

        <!-- Page 21: Deep Palm & Face Interpretations (1) -->
        <div class="page">
          <div class="section-header">✦ Deep Interpretations (Mounts)</div>
          <div class="glass-card">
            <p>Beyond the lines, the 'Mounts' on your palm reveal hidden reservoirs of energy.</p>
            <div class="career-card">
              <strong>The Mount of Jupiter:</strong> Prominent and firm. This is the indicator of your innate desire to lead and govern. It confirms your capacity for high-office.
            </div>
            <div class="career-card">
              <strong>The Mount of Apollo:</strong> Well-developed, suggesting a strong appreciation for the arts and a 'Golden Touch' in business ventures.
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">21</div>
        </div>

        <!-- Page 22: Deep Palm & Face Interpretations (2) -->
        <div class="page">
          <div class="section-header">✦ Micro-Physiognomy</div>
          <div class="glass-card">
            <p>The subtle markers on your face, such as the <strong>Philtrum depth</strong> and <strong>Ear lobe shape</strong>, reveal your long-term wealth accumulation pattern.</p>
            <div class="highlight-box">
              "Your facial markers suggest that wealth will come to you through 'Authority-based Assets'—assets that grow because of your personal brand and expertise."
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">22</div>
        </div>

        <!-- Page 23: Micro-Milestones Roadmap (Year 1) -->
        <div class="page">
          <div class="section-header">✦ Micro-Milestones (Year 1)</div>
          <div class="glass-card">
            <div style="display: grid; gap: 15px;">
              <div style="padding: 15px; border-bottom: 1px solid rgba(255,255,255,0.1);"><strong>Q1:</strong> Audit current skills. Identify the top 1% skill in your niche.</div>
              <div style="padding: 15px; border-bottom: 1px solid rgba(255,255,255,0.1);"><strong>Q2:</strong> Launch a public-facing project or thought leadership initiative.</div>
              <div style="padding: 15px; border-bottom: 1px solid rgba(255,255,255,0.1);"><strong>Q3:</strong> Secure a high-level mentor or joined an elite professional circle.</div>
              <div style="padding: 15px; border-bottom: 1px solid rgba(255,255,255,0.1);"><strong>Q4:</strong> Negotiate for 20%+ increase in responsibility or compensation.</div>
            </div>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">23</div>
        </div>

        <!-- Page 24: Micro-Milestones Roadmap (Year 2-3) -->
        <div class="page">
          <div class="section-header">✦ Scaling Milestones</div>
          <div class="glass-card">
            <h3 style="color: #fff; font-size: 20px; margin-bottom: 15px;">The Leap Phase</h3>
            <p><strong>Month 18:</strong> This is a critical cosmic window. A major opportunity will arrive via an unexpected connection. Be ready to pivot.</p>
            <p><strong>Month 30:</strong> Your leadership transition should be complete. You should now be focused on 10x impact rather than 10% improvements.</p>
          </div>
          <div class="footer">${t.footer}</div>
          <div class="page-num">24</div>
        </div>

        <!-- Page 25: Priority Generation & Final Master Conclusion -->
        <div class="page">
          <div class="section-header">✦ Master Priority List</div>
          <div class="glass-card">
            <p>As a <strong>Cosmic Master</strong>, your focus should be on the 'Vital Few' actions that drive 80% of your results.</p>
            <ol style="color: #fff; margin-left: 25px; line-height: 2;">
              <li><strong>Mastery:</strong> Consolidate your core expertise.</li>
              <li><strong>Authority:</strong> Build a recognizable professional brand.</li>
              <li><strong>Network:</strong> Curate a high-value circle of influence.</li>
            </ol>
            <div style="margin-top: 40px; padding: 30px; background: ${accentColor}22; border-radius: 20px; border: 1px solid ${accentColor}44;">
              <p style="font-size: 18px; color: #fff;"><strong>Final Master Verdict for ${userName}:</strong></p>
              <p>You are destined for a role that bridges the gap between today's reality and tomorrow's possibilities. Lead with courage, for the universe is aligned in your favor.</p>
            </div>
          </div>
          <div class="footer">
            <p style="font-weight: 900; color: #fff; letter-spacing: 3px; margin-bottom: 5px;">LIFE ON 66 • THE ULTIMATE COSMIC MASTERPIECE</p>
            <p>Generated for the exclusive use of ${userName}</p>
          </div>
          <div class="page-num">25</div>
        </div>
      ` : ''}
    </body>
    </html>
  `;

  return html;
}

async function generatePDF(analysis, language, fullData, tier, userName) {
  let browser;
  try {
    console.log(`[PDF] Starting Puppeteer launch for ${tier} report...`);
    const { findChromeExecutable } = require('../utils/puppeteerHelper');
    const executablePath = findChromeExecutable();
    
    const launchOptions = {
      headless: true,
      args: [
        '--no-sandbox', 
        '--disable-setuid-sandbox', 
        '--disable-dev-shm-usage', 
        '--disable-gpu',
        '--no-zygote',
        '--single-process',
        '--disable-software-rasterizer'
      ],
    };

    if (executablePath) {
      console.log(`[PDF] Using explicit executablePath: ${executablePath}`);
      launchOptions.executablePath = executablePath;
    } else if (process.env.NODE_ENV === 'production' || process.env.PORT) {
      throw new Error(`Chrome Headless Shell executable not found in puppeteer_cache. Please trigger "Clear Build Cache & Deploy" on Render.`);
    }

    browser = await puppeteer.launch(launchOptions);
    
    console.log('[PDF] Opening new page...');
    const page = await browser.newPage();
    const html = createHTMLContent(analysis, language, fullData, tier, userName);
    
    console.log('[PDF] Setting content and waiting for assets...');
    // networkidle0 is important to ensure images load
    await page.setContent(html, { 
      waitUntil: 'networkidle0',
      timeout: 60000 
    });
    
    console.log('[PDF] Generating PDF buffer...');
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: 0, right: 0, bottom: 0, left: 0 }
    });

    console.log('[PDF] Success! Total bytes:', pdf.length);
    return pdf;
  } catch (error) {
    console.error('[PDF] Error during generation:', error);
    throw error;
  } finally {
    if (browser) await browser.close();
  }
}

module.exports = { generatePDF };
